# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_usUelijdb7A8rqRuCogpnVqwAEYvsE
"""

import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1], [2], [3], [4], [5]])
Y = np.array([2, 4, 6, 8, 10])
model = LinearRegression()

import numpy as np
X = np.array([[1], [2], [3], [4], [5]])
Y = np.array([2, 4, 6, 8, 10])
print(X)
print(Y)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, Y)

X_new = np.array([[6]])
prediction = model.predict(X_new)

print(prediction)

np.random.seed(0)
X = np.linspace(-5, 5, 100)
Y = X**2 + np.random.normal(0, 4, size = 100)