# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTqEwZCDr3nGFwvfe79bLjXKsn95XgPF
"""

# Titanic Survival Prediction - Logistic Regression

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# --------------------------------------------------
# 1. Load the dataset
# --------------------------------------------------

df = pd.read_csv("titanic.csv")

print("First 5 rows:")
print(df.head())

print("\nShape of dataset:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nDataset information:")
df.info()

print("\nStatistical description:")
print(df.describe())

print("\nMissing values:")
print(df.isnull().sum())


# --------------------------------------------------
# 2. Exploratory Data Analysis (EDA)
# --------------------------------------------------

# Survival count
sns.countplot(x="survived", data=df)
plt.title("Titanic Survival Count")
plt.xlabel("Survived")
plt.ylabel("Count")
plt.show()


# Survival by gender
sns.countplot(x="sex", hue="survived", data=df)
plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()


# Survival by passenger class
sns.countplot(x="pclass", hue="survived", data=df)
plt.title("Survival by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Count")
plt.show()


# --------------------------------------------------
# 3. Select Features and Target
# --------------------------------------------------

features = [
    "pclass",
    "sex",
    "age",
    "sibsp",
    "parch",
    "fare",
    "embarked"
]

X = df[features].copy()
y = df["survived"]


# --------------------------------------------------
# 4. Handle Missing Values
# --------------------------------------------------

# Age is numerical → use median
X["age"] = X["age"].fillna(X["age"].median())

# Embarked is categorical → use mode
X["embarked"] = X["embarked"].fillna(X["embarked"].mode()[0])

print("\nMissing values after filling:")
print(X.isnull().sum())


# --------------------------------------------------
# 5. Convert Categorical Data into Numbers
# --------------------------------------------------

X = pd.get_dummies(
    X,
    columns=["sex", "embarked"],
    drop_first=True
)

print("\nFeatures after encoding:")
print(X.head())

print("\nFeature columns:")
print(X.columns)


# --------------------------------------------------
# 6. Train-Test Split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining data size:", X_train.shape)
print("Testing data size:", X_test.shape)


# --------------------------------------------------
# 7. Feature Scaling
# --------------------------------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# --------------------------------------------------
# 8. Logistic Regression Model
# --------------------------------------------------

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

print("\nModel training completed!")


# --------------------------------------------------
# 9. Prediction
# --------------------------------------------------

y_pred = model.predict(X_test_scaled)

print("\nFirst 20 predictions:")
print(y_pred[:20])


# --------------------------------------------------
# 10. Model Evaluation
# --------------------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:")
print(accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


# --------------------------------------------------
# 11. Confusion Matrix
# --------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()